### PR TITLE
check if component is mounted before setting state

### PR DESCRIPTION
**Pull request by mikhuang**
I was having issues with deleting an item from the store causing many components to unmount and then having reflux attempt to set state. Perhaps there is a better way of doing this?

### CODE REVIEW

**Comment by Dignifiedquire** [comment]
I think you might be running into the same issue that is described/fixed in this commit: https://github.com/ianobermiller/nuclearmail/commit/23b5f7c8526e43d02a2bc90994767b83d5d7dbd2

He describes that `isMounted` is `false` during the mount phases, screwing up any attempts to call `setState`/`replaceState`.

**Comment by twisterghost** [comment]
Need this for something. Is there anything holding this up?

**Comment by LongLiveCHIEF** [comment]
:+1: . If we don't hear from @spoike in the next 12 hours (it's about bedtime in his part of the world), I'll accept this MR.

**Comment by twisterghost** [comment]
Great - I think this will be a fantastic addition, especially for the world of component testing, where unmounts happen all the time

**Comment by spoike** [comment]
@LongLiveCHIEF, spoike says :+1:

**Comment by LongLiveCHIEF** [comment]
Sounds good. Merged this, a few other public PR's and some bug fixes into a `0.2.8` release that should be ready to review on develop shortly.

**Pull request closed without merging**
