### PR TITLE
connect: Use replaceState() instead of setState()

### LINKED ISSUE #242: connect() should use replaceState()
https://github.com/spoike/refluxjs/blob/master/src/connect.js#L17 should be changed to use `replaceState()` instead of `setState()`.

If my store has data `{a: 5, b: 10}` and the data changes to `{a: 5, c: 15}` the state of the connected components will now be `{a: 5, b: 10, c: 15}`. I consider this a bug since I expected the `connect()` function to always sync the store data with the component state.

### PR DESCRIPTION
**Pull request by Turbo87**
fixes #242

### CODE REVIEW

**Comment by Turbo87** [comment]
I haven't used `connectFilter()` yet, so I don't know whether that should be changed too.

**Comment by spoike** [comment]
See #133.

If you document this behavior in the README file, I'll consider merging this PR for the next release.

**Comment by svenanders** [comment]
Given that React is considering dropping replaceState, this might not be a good idea
https://github.com/facebook/react/issues/2843

**Comment by Turbo87** [comment]
@svenanders seems they really deprecated it... (http://facebook.github.io/react/blog/2015/02/24/react-v0.13-rc1.html)

still I think that using `setState()` is the wrong thing to do, but I don't know how to resolve this issue.

**Comment by askholme** [comment]
@Turbo87 An easy and pretty fix is simply to use a key with connect. Then setState will work fine. It's only when your immutable object should be directly set as this.state that you will get trouble with setState. 

See the second example on https://github.com/facebook/immutable-js/wiki/Immutable-as-React-state where setState is used together with an immutable data structure .

The similiar approach for reflux is to supply stateKey to connect e.g.
```
mixins: [Reflux.connect(statusStore,"currentStatus")],
```

**Comment by Turbo87** [comment]
@askholme I am aware that using a key works around this issue, but since `connect()` is advertised as working without a key too I consider this a bug. Since `replaceState()` is deprecated in react now I would propose to deprecate the key-less version of `connect()` too, as it simply doesn't work as expected.

@spoike any thoughts on that?

**Comment by spoike** [comment]
@Turbo87 Yeah, we should make the key parameter for `connect()` mandatory.

**Comment by ivan-kleshnin** [comment]
I have a few related questions:
1) Why not just merge `connect` and `connectFilter`? Seems a waste to multiply them, when `connect` could easily accept optional filter param.

2) Anyone considered wrapped store states? I mean store with a list of models in form
`{models: [...]}, not `[...]`). That would mimic component's approach to state.

Now: `Store.state` <==> `Component.state[key]`.
Possible: `Store.state[someKey]` <==> `Component.state[otherKey]`.

Now we're enforced to keep additional state values in `Store._someUnderscoredVar` and keep in mind those two different approaches to state modelling.

**Comment by LongLiveCHIEF** [comment]
@ivan-kleshnin yes and yes, but responding to either of those questions in this thread would make it grow unbearable. I have thoughts on these, but they'd be better as discussions in Slack instead of a mega-thread in this issue.

**Comment by LongLiveCHIEF** [comment]
This needs to be handled as a bug, but the PR won't fix the issue. Will open new issue to work on this.

**Pull request closed without merging**
