### PR TITLE
Added back-to-top link for each section.

### PR DESCRIPTION
**Pull request by srph**
I got this idea from [johnpapa/angularjs-styleguide](https://github.com/johnpapa/angularjs-styleguide#application-structure-lift-principle). Might improve the doc :tada:

### CODE REVIEW

**Comment by srph** [comment]
Any thoughts why this is failing?

**Comment by spoike** [comment]
Travis sometimes fails randomly due to some issue with their build environment.

**Comment by spoike** [comment]
Thanks for the contribution!

**Comment by srph** [comment]
Thanks, too, for this wonderful work :+1:

**Pull request merged**
