### PR TITLE
Ensure triggerPromise original promise

### LINKED ISSUE #228: Action.triggerPromise is probaby not what you expect
The idea of `triggerPromise` is that you can "trigger" and action, and collect the promise of that action completion and result, and therefor it's result.  But, here's the rub, Actions are EVENTS.  So, you are returned a promise resolved when any trigger of the action is completed.  I've probably lost you, but let's see this play-out.

Let's take a simple Reflux component layout…

```jsx
RefreshTransactions = {}
RefreshTransactions.load = Reflux.createAction({async: true})
RefreshTransactions.load.listenPromise(params => api.promise(params))

TransactionStore = Reflux.createStore({
  listenables: [RefreshTransactions],
  data: [],
  getInitalState(){
    return this.data
  },
  onLoadCompleted(data){
    this.trigger(this.data = data)
  }
  onLoadFailed(){
    this.trigger(this.data = [])
  }
})

TransactionView = React.createClass({
  mixins: [Reflux.connect(TransactionStore, 'transactions')],
  render(){
    return <ul>{this.state.transactions.map(t =>
      <li>{t.name} {t.amount} {t.date}</li>
    }</ul>
  }
})

app.use(function(req, res, next) {
  RefreshTransactions
    .triggerPromise(req.query.accountId)
    .then(function(data){
      TransactionStore.data = data
      res.send(React.renderToString(<TransactionView accountId={req.query.accountId} />))
    })
})
```

Query-strings are clearly a bad idea, esp with accounts, but I'm trying to show something trivial. Here's the problem on the server, let's say three requests come in around the same time.
* /transactions?accountId=1
* /transactions?accountId=2
* /transactions?accountId=3

So, your isomorphic app runs out to grab that data from the api.  When the first response comes in from the API… the action fulfills *all* promises.  Which means you'll end up rendering the same result for all three requests.

Now, I'm not dealing with accounts and transactions, but I do want a promise of when *my* trigger is done.  You can solve this simple example in a dozen different ways, but they are likely all stepping out using Reflux.  Is there a way to do this in Reflux?

### PR DESCRIPTION
**Pull request by robcolburn**
Closes #228 (see that issue for full explanation)

Unfortunately, this involves a bit of dirty monkey-patching, so I welcome suggestions.

### CODE REVIEW

**Comment by robcolburn** [comment]
I've made the monkey-patching less dirty and more scoped, and written a test which describes the problem.

If you cherry-pick the test in c10854d, then you'll be able to see my original problem.

**Comment by robcolburn** [comment]
@spoike - resolved conflicts

**Comment by spoike** [comment]
Cool, thanks!

**Comment by robcolburn** [comment]
Thanks for merging!

-- 
--
Rob Colburn

**Pull request merged**
