### PR TITLE
Switch nextTick to setImmediate

### PR DESCRIPTION
**Pull request by Laiff**
This gives a significant increase in processing speed events, particularly in complex relationships

### CODE REVIEW

**Comment by spoike** [comment]
`utils.js` is available in `Reflux._` by the way. Don't remember when it was added though...

**Comment by spoike** [comment]
Things to do

* [ ] Readme should have info about switching to `setimmediate2`

**Comment by Dashed** [comment]
Another setImmediate fork: https://github.com/calvinmetcalf/macrotask
This is rather forked much earlier at https://github.com/YuzuJS/setImmediate/commit/6dd6a2dd3162f15848ca4d609d70b778b9b59261

**Comment by ooflorent** [comment]
`process.nextTick` browser's implementation got a huge performance boost (defunctzombie/node-process#29). Maybe this PR is not pertinent anymore.

**Comment by Dashed** [comment]
Be very aware that `setimmediate` isn't patched for this bug: https://github.com/YuzuJS/setImmediate/issues/35

So `setimmediate2` or `macrotask` is to be used alternatively.

---

IMO, this PR shouldn't be merged b/c it introduces one more dependency. Plus, there's a reason why that `exports.nextTick` is overridable; so that end-devs to use their favourite flavour of `nextTick`.

**Comment by spoike** [comment]
@Dashed I'm not going to merge this PR, as it introduces another dependency that can instead be configured through nextTick. I'm really want to keep reflux dependency-free (with the exception of eventemitter since reflux is dependent on the pubsub functionality and I can't be bothered to reimplement that).

I only have this issue open as a reminder to update the README.

**Pull request closed without merging**
