### PR TITLE
allow using react version 0.14.0-alpha3

### PR DESCRIPTION
**Pull request by spirinvladimir**

### CODE REVIEW

**Comment by LongLiveCHIEF** [comment]
v0.2x hasn't been tested against React 0.14x yet, and we're soon moving to v0.3, which will remove react as a dependency for Reflux altogether.

At the moment, having React listed as a peer dependency does not prevent you from using versions of React beyond what we've specified, but is our way of saying that we can't currently support issues that arise from using it in conjunction with Reflux.

Thanks!

**Comment by BrandonCouts** [comment]
It would be really nice if the peer dependency could be removed. I'm trying to get an instance of react-starter-kit going using reflux, and the starter kit is using the react@0.14.0-beta3. I thought that the idea  of flux was that its suppose to be independent of react? I can't find any reason for the dependency  in the code at a glance. Why is it still a dependency for reflux, and reflux-core? Also if you don't support edge, then just say so in the docs, and leave the hard decisions for the developers on the edge, eh? For me its too late, as I've already integrated it, but it will be harder for me to install between machines now.

**Comment by LongLiveCHIEF** [comment]
This is open source software, and we only have 2 maintainers, who are focused on other work at the moment.

This is pretty common amongst OS software, and you need to consider that when selecting the software you use.

**Comment by BrandonCouts** [comment]
This is common I agree, but I think the dependency does not exist?

**Pull request closed without merging**
