### PR TITLE
Suggesting another example app

### PR DESCRIPTION
**Pull request by VladimirPal**
Add another example app

### CODE REVIEW

**Comment by kevinsimper** [comment]
Nice example, but I don't know if it is too extensive to be an example.

**Comment by VladimirPal** [comment]
@kevinsimper Yeah, but you already have lite examples. I believe such example can be very useful.

**Comment by LongLiveCHIEF** [comment]
@VladimirPal I agree, I'm going to merge it and release this with `0.2.8`.

**Comment by LongLiveCHIEF** [comment]
merged in c36d6c3

**Pull request closed without merging**
