### PR TITLE
Add Statefulness to StoreMethods

### PR DESCRIPTION
**Pull request by stephen**
Internally uses [Immutable.js](https://github.com/facebook/immutable-js) to hold immutable state. Addresses #290.

thoughts, @spoike?

### CODE REVIEW

**Comment by stephen** [comment]
Hm, realizing that this doesn't address having multiple `getInitialState` functions on the class. Believe React's behavior for this is to merge all keys as long as there are no duplicates.

**Comment by LongLiveCHIEF** [comment]
We're setting up the v0.3.0 branch right now, and it will use observables (initially via [RxJS](http://reactive-extensions.github.io/RxJS/)). This will be a breaking change for this commit.

0.3.0 will also introduce a more structured plugin api, which you'll be able to register this to. If you'd like to work with me on that as I move through this work in the next 

The 0.2.8 branch I'm merging later tonight will also fix  a problem caused by use of `replaceState`. See #243

**Comment by stephen** [comment]
Sure, I'm happy to work with you on this. I've been using a mixin to add state in my application in the meantime.

Can you clarify what the changes will be around the plugins API + RxJS (i.e. what the breaking changes will be for the latter), and if there's something I can look at to adapt this PR?

re: `replaceState`, I'm taking that to mean I should just drop `replaceState` support, given that's it's being deprecated from react?

**Comment by LongLiveCHIEF** [comment]
I don't know many specifics yet around what breaking changes will be. But yes, drop `replaceState` since it's being deprecated from React.

**Comment by stephen** [comment]
Hmm, okay. What do you suggest the right steps are for working on this? Can open another PR without `replaceState`, but do you have thoughts on where this should live with the new plugins API? Does any code exist for it currently that can be referenced?

The [current 3.0.0-alpha](https://github.com/spoike/refluxjs/blob/v0.3.0-alpha/src/createStore.js) branch still looks like it's pulling from `StoreMethods`.

**Comment by LongLiveCHIEF** [comment]
I'm working on it. Give me a few days and check back.

**Comment by stephen** [comment]
Okay - thanks for clarifying!

**Comment by LongLiveCHIEF** [comment]
@stephen are you on reactiflux slack? if so, you'll be able to collab with me in real-time. Ping me there (@ngdchief), and I'll run my current thought process through you so you have a place to start.

**Pull request closed without merging**
